name    'qrohlf-dokku'
version '0.1.0'
source 'UNKNOWN'
author 'qrohlf'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/git', '>= 0'
dependency 'puppetlabs/vcsrepo', '>= 0'
